"""Generate `airplaya/crypto/fp_replies.py` from the vendored C table.

The four 142-byte FairPlay `fp-setup` stage-1 replies are constants captured from
an Apple receiver. They live in `native/playfair/fairplay_playfair.c` (LGPL-2.1,
from UxPlay). Transcribing 568 bytes of hex by hand is a good way to introduce a
silent handshake failure, so we parse them out of the C source instead.

Run this only when the vendored C source changes; the output is committed.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
C_SOURCE = ROOT / "native" / "playfair" / "fairplay_playfair.c"
OUTPUT = ROOT / "src" / "airplaya" / "crypto" / "fp_replies.py"

BYTE_RE = re.compile(r"0x([0-9a-fA-F]{2})")


def parse_array(text: str, name: str, expect_rows: int, expect_len: int) -> list[bytes]:
    """Pull the `{...}` initialiser of `name` out of `text` and split it into rows."""
    start = text.index(name)
    start = text.index("{", start)
    depth = 0
    for end, ch in enumerate(text[start:], start):
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                break
    body = text[start : end + 1]

    rows = []
    if expect_rows == 1:
        rows.append(bytes(int(m, 16) for m in BYTE_RE.findall(body)))
    else:
        # Strip the outer braces, then each remaining {...} group is one row.
        for group in re.findall(r"\{([^{}]*)\}", body[1:-1]):
            rows.append(bytes(int(m, 16) for m in BYTE_RE.findall(group)))

    if len(rows) != expect_rows:
        raise SystemExit(f"{name}: expected {expect_rows} rows, parsed {len(rows)}")
    for i, row in enumerate(rows):
        if len(row) != expect_len:
            raise SystemExit(f"{name}[{i}]: expected {expect_len} bytes, parsed {len(row)}")
    return rows


def format_blob(data: bytes, indent: str) -> str:
    hexed = data.hex()
    chunks = [hexed[i : i + 64] for i in range(0, len(hexed), 64)]
    lines = "\n".join(f'{indent}    "{c}"' for c in chunks)
    return f"bytes.fromhex(\n{lines}\n{indent})"


def main() -> int:
    text = C_SOURCE.read_text(encoding="utf-8", errors="replace")
    replies = parse_array(text, "reply_message", expect_rows=4, expect_len=142)
    header = parse_array(text, "fp_header", expect_rows=1, expect_len=12)[0]

    parts = [
        '"""FairPlay `fp-setup` constants. GENERATED by scripts/gen_fp_replies.py."""',
        "",
        "# Stage-1 replies, indexed by the mode byte at offset 14 of the client request.",
        "SETUP_REPLIES: tuple[bytes, ...] = (",
    ]
    for reply in replies:
        parts.append(f"    {format_blob(reply, '    ')},")
    parts += [
        ")",
        "",
        "# Prefix of the 32-byte stage-2 reply; the remaining 20 bytes are echoed",
        "# from the client's request.",
        f"HANDSHAKE_HEADER: bytes = {format_blob(header, '')}",
        "",
    ]
    OUTPUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}: {len(replies)} replies, {len(header)}-byte header")
    return 0


if __name__ == "__main__":
    sys.exit(main())
